import { Category } from './types';

const categories: Category[] = [
  {
    category: 'popular',
    icon: 'GiTrophy',
    keywords: [
      '#_isp',
      '#apfmagazine',
      '#artofvisuals',
      '#aspfeatures',
      '#bcncollective',
      '#burnmagazine',
      '#burnmyeye',
      '#capturestreets',
      '#citygrammers',
      '#curiouscameraclub',
      '#dpsp_street',
      '#dreaminstreets',
      '#everybodystreet',
      '#eyephotomagazine',
      '#f22bestphoto',
      '#friendsinstreets',
      '#fromstreetswithlove',
      '#gf_streets',
      '#hcsc_street',
      '#insidephotos',
      '#knowthismind',
      '#lensculture',
      '#lensculturestreets',
      '#life_is_street',
      '#magnumphotos',
      '#myspc',
      '#nonstopstreet',
      '#observecollective',
      '#ourstreets',
      '#rawstreetphotogallery',
      '#rawurbanshots',
      '#snapthestreetbeat',
      '#soulofstreet',
      '#spi_collective',
      '#spicollective',
      '#storyofthestreet',
      '#street_avengers',
      '#street_is_life',
      '#street_storytellers',
      '#street_storytelling',
      '#streetactivity',
      '#streetcapture',
      '#streetclassics',
      '#streetdreamsmag',
      '#streetfinder',
      '#streetgallerymagazine',
      '#streetgrammer',
      '#streetgrammers',
      '#streethunters',
      '#streetizm',
      '#streetleaks',
      '#streetlensmag',
      '#streetlife_awards',
      '#streetmagazines',
      '#streetmoment',
      '#streetouss',
      '#streetphotographerscommunity',
      '#streetphotographersmagazine',
      '#streetphotographyinternational',
      '#streetphotographyworldwide',
      '#streets_in_motion',
      '#streets_storytelling',
      '#streets_unseen',
      '#streets_vision',
      '#streetsansfrontieres',
      '#streetscape',
      '#streetscene',
      '#streetsgrammer',
      '#streetshared',
      '#streetsvision',
      '#streetweekly',
      '#streetxstory',
      '#streetziers',
      '#streetzim',
      '#sublimestreet',
      '#supersweetstreet',
      '#sweet_street_beat',
      '#tdmmag',
      '#thestreephers',
      '#timeless_streets',
      '#today_streets',
      '#urbanstreetphotogallery',
      '#wearethestreets',
      '#worldviewmag',
      '#zonestreet',
      '#street_unseen',
    ],
  },
  {
    category: 'portrait',
    icon: 'GiSuspicious',
    keywords: [
      '#peopleinframe',
      '#portraitstreet',
      '#streetportraits',
      '#streetportraiture',
      '#streetportraitphotography',
      '#streetportrait',
      '#urbanportrait',
    ],
  },
  {
    category: 'architecture',
    icon: 'GiModernCity',
    keywords: ['#archilovers', '#architecturelovers', '#streetarchitecture'],
  },
  {
    category: 'candid',
    icon: 'GiSpy',
    keywords: [
      '#candid',
      '#candidphotography',
      '#candidshot',
      '#candids',
      '#candidphoto',
      '#candidclick',
      '#candidmoments',
      '#candida',
      '#candidphotographer',
      '#candidshots',
      '#candidmoment',
      '#candidcamera',
      '#CandidMemories',
      '#candidmotherhood',
      '#candidportrait',
      '#candidsandra',
      '#candidslumber',
      '#candidphotos',
      '#candidasa',
      '#candidpic',
    ],
  },
  {
    category: 'color',
    icon: 'GiPalette',
    keywords: [
      '#color_street',
      '#colour_street',
      '#spi_colour',
      '#streetcolor',
      '#streetcolour',
      '#colorstreets',
    ],
  },
  {
    category: 'b&w',
    icon: 'GiBlackball',
    keywords: [
      '#friendsinbnw',
      '#bnw_captures',
      '#bnw_drama',
      '#bnw_demand',
      '#bnw_life',
      '#ig_photostars_bw',
      '#insta_bw',
      '#bnw_magazine',
      '#streetphoto_bw',
      '#streetphotography_bw',
      '#monochrome',
      '#blackandwhitephotography',
      '#blackandwhitephoto',
      '#monochromatic',
    ],
  },
  {
    category: 'film',
    icon: 'GiFilmStrip',
    keywords: [
      '#analogfeatures',
      '#analoguevibes',
      '#believeinfilm',
      '#buyfilmnotmegapixels',
      '#buyfilmnotpixels',
      '#filmcamera',
      '#filmcommunity',
      '#filmfeed',
      '#filmisalive',
      '#grainisgood',
      '#onfilm',
      '#shootfilm',
      '#staybrokeshootfilm',
      '#filmic_streets',
      '#filmnotdead',
    ],
  },
  {
    category: 'documentary',
    icon: 'GiNewspaper',
    keywords: ['#photodocumentary'],
  },
  {
    category: 'visual poetry',
    icon: 'GiBalloons',
    keywords: [
      '#apricotmagazine',
      '#artclassified',
      '#boyhill',
      '#broadmag',
      '#classicsmagazine',
      '#dreamermagazine',
      '#espritmag',
      '#etczine',
      '#fisheyemag',
      '#fivesixmag',
      '#indiependentmag',
      '#ithosmag',
      '#itsthatnice',
      '#magnificomagazine',
      '#makemeseemag',
      '#myamericanvision',
      '#noicemag',
      '#oftheafternoon',
      '#optionmag',
      '#ourmag',
      '#paperjournalmag',
      '#peachestate',
      '#phroommagazine',
      '#portbox',
      '#realismag',
      '#rentalmag',
      '#somewheremagazine',
      '#subjectivelyobjective',
      '#taintedmag',
      '#thinkverylittle',
      '#thisaintartschool',
      '#truecolormag',
      '#wtns',
    ],
  },
];

export default (req, res): void => {
  res.statusCode = 200;
  res.json(categories);
};
